polar:
  greeting: "Welcome to the catalog from a fresh config server"

server:
  port: 8300
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8200
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
